config/routes.rb
Mountie::Engine.routes.draw do
  resources :entries
  root to: "test#index"
end

app/models/mountie/entry.rb
module Mountie
  class Entry < ActiveRecord::Base
    validates_presence_of :data
  end
end

app/controllers/mountie/application_controller.rb
module Mountie
  class ApplicationController < ActionController::Base
  end
end

app/controllers/mountie/entries_controller.rb
class Mountie::EntriesController < Mountie::ApplicationController
  def index
    @entries = Mountie::Entry.all
  end

  def show
    @entry = Mountie::Entry.find params[:id]
  end

  def new
    @entry = Mountie::Entry.new
  end

  def create
    @entry = Mountie::Entry.create params[:entry]
    redirect_to @entry
  end

  def edit
    @entry = Mountie::Entry.find params[:id]
  end

  def update
    @entry = Mountie::Entry.find params[:id]
    @entry.update_attributes params[:entry]
    redirect_to @entry
  end

  def destroy
    Mountie::Entry.destroy params[:id]
    redirect_to entries_path
  end
end

app/controllers/mountie/test_controller.rb
class Mountie::TestController < Mountie::ApplicationController
  def index
    render text: Mountie.configuration.name
  end
end

app/helpers/mountie/application_helper.rb
module Mountie
  module ApplicationHelper
  end
end

app/views/layouts/mountie/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mountie</title>
  <%= stylesheet_link_tag    "mountie/application", :media => "all" %>
  <%= javascript_include_tag "mountie/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mountie/entries/_form.html.erb
<%= form_for entry do |f| %>
  <div>
    <%= f.label :data %>
    <%= f.text_field :data %>
  </div>
  <div>
    <%= f.submit %>
  </div>
<% end %>

app/views/mountie/entries/edit.html.erb
<h1>Edit Entry</h1>

<%= render 'form', entry: @entry %>

app/views/mountie/entries/index.html.erb
<h1>Entries</h1>

<ul>
  <% for entry in @entries %>
    <%= content_tag :li, link_to(entry.data, entry) %>
  <% end %>
</ul>

<%= link_to "New Entry", new_entry_path %>

app/views/mountie/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form', entry: @entry %>

app/views/mountie/entries/show.html.erb
<h1>Entry</h1>

<p><%= @entry.data %></p>

<%= link_to "Edit Entry", edit_entry_path(@entry) %><br />
<%= link_to "Delete Entry", entry_path(@entry), method: :delete, confirm: "Are you sure?" %><br />
<%= link_to "All Entries", entries_path %>